Changed the image build and its dir structure
FFIG/rest-api pull request #6
Opened 2017-02-11 13:27 UTC by petr-tik

Removed one extra layer of directories.
Before:
/home/ffig/ffig-master
/home/ffig/flask

Now:
/home/ffig-master/
/home/flask

pip2 install to guarantee installing flask for py2

remove RUN .. curl, because curl wasn't installed - docker build was breaking
Instead ADD from the github link

Won't expose anymore - we need port binding in
docker run -p 5000:5000, not exposing portts

2017-02-11 13:48 UTC, ajbennieston requested changes

2017-02-11 13:48 UTC, ajbennieston commented on Dockerfile
> +    rm -f home/master.zip
We should install `curl` into the base image. This change makes two layers in this image, but the base image already has an `apt-get install ...` that we can just add `curl` to.

2017-02-11 14:11 UTC, petr-tik commented on Dockerfile
> +    rm -f home/master.zip
Are you happy with the rest?

2017-02-11 15:08 UTC, ajbennieston commented on Dockerfile
> +    rm -f home/master.zip
Yeah. If I didn't comment on it, I'm happy with it.

2017-02-11 15:08 UTC, ajbennieston submitted a review, later dismissed

2017-02-11 15:12 UTC, ajbennieston commented
Sorry; approved too soon. Need to change the ADD/RUN back to a single RUN once the base image has been re-built.

2017-02-12 00:12 UTC, ajbennieston commented on Dockerfile
> +    unzip ffig-master.zip && \
just `master.zip`?

2017-02-13 21:14 UTC, petr-tik commented
@ajbennieston please review the final changes

2017-02-13 22:22 UTC, ajbennieston approved these changes

2017-02-13 22:22 UTC, merged